server:
  port: 8080
  sessionTimeout: 30
  error:
    path: /error
jasypt:
  encryptor:
    password: test
spring:
  application:
    name: diamond
  profiles:
    active: dev
  datasource:
    #主库(1)
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://61.174.60.20:1433;DatabaseName=moldate_system
      # sa
      username: ENC(G4nTINcbnHx5W8hHNJhvfA==)
      password: ENC(k7ehZUOi3GDmyzqu0J5wFTwly+lIdpup)
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initial-size: 1
      min-idle: 1
      max-active: 5
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j,config
    #从库(N)
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://61.174.60.20:1433;DatabaseName=AnHui_HeFeiNew
      # sa
      username: ENC(G4nTINcbnHx5W8hHNJhvfA==)
      password: ENC(k7ehZUOi3GDmyzqu0J5wFTwly+lIdpup)
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initial-size: 1
      min-idle: 1
      max-active: 5
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j,config
  mvc:
    view:
      prefix: /static/
      suffix: .html


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ml.diamond.entity
  #config-location: classpath:mybatis-config.xml

#日志
logging:
  level:
    ROOT: DEBUG
    org.springframework: INFO
    org.springframework.data: INFO
    org.mybatis: DEBUG
    com.ml.diamond: DEBUG
  file: ../logs/logback.log
